let camisetas = [
    { id:1, nombre: 'Qatar',precio: 100, marca: "Nike", img: "img/qatar.jpg", cantidad: 1,},
    { id:2, nombre: 'Ecuador', precio: 50, marca: "Marathon", img:"img/ecuador.webp",cantidad: 1,},
    { id:3, nombre: 'Senegal', precio: 100, marca: "Puma", img:"img/senegal.webp",cantidad: 1,},
    { id:4, nombre: 'Holanda', precio: 115, marca: "Nike", img:"img/holanda.jpg",cantidad: 1,},
    { id:5, nombre:'Iran', precio: 100, marca: "Majid", img:"img/iran.jpg",cantidad: 1,},
    { id:6, nombre:'USA', precio: 100, marca: "Nike", img:"img/usa.webp",cantidad: 1,},
    { id:7, nombre:'Gales', precio: 100, marca: "Adidas", img:"img/wales.webp",cantidad: 1,},
    { id:8, nombre:'Argentina', precio: 100, marca: "Adidas", img:"img/argentina.webp",cantidad: 1,},
    { id:9, nombre:'KSA', precio: 100, marca: "Nike", img:"img/ksa.webp",cantidad: 1,},
    { id:10, nombre:'Mexico', precio: 100, marca: "Adidas", img:"img/mexico.webp",cantidad: 1,},
    { id:11, nombre:'Polonia', precio: 100, marca: "Nike", img:"img/POLONIA.webp",cantidad: 1,},
    { id:12, nombre:'Francia', precio: 100, marca: "Nike", img:"img/francia.webp",cantidad: 1,},
    { id:13, nombre:'Australia', precio: 100, marca: "Nike", img:"img/australia.webp",cantidad: 1,},
    { id:14, nombre:'Dinamarca', precio: 100, marca: "Hummel", img:"img/dinamarca.webp",cantidad: 1,},
    { id:15, nombre:'Tunez', precio: 100, marca: "Kappa", img:"img/tunez.jpg",cantidad: 1,},
    { id:16, nombre:'España', precio: 100, marca: "Adidas", img:"img/spain.webp"},
    { id:17, nombre:'Costa Rica', precio: 100, marca: "New Balance", img:"img/costa-rica.jfif", cantidad: 1,},
    { id:18, nombre:'Alemania', precio: 100, marca: "Adidas", img:"img/alemania.webp",cantidad: 1,},
    { id:19, nombre:'Japon', precio: 100, marca: "Adidas", img:"img/japon.webp",cantidad: 1,},
    { id:20, nombre:'Belgica', precio: 100, marca: "Adidas", img:"img/belgica.webp",cantidad: 1,},
    { id:21, nombre:'Canada', precio: 100, marca: "Nike", img:"img/canada.jpg",cantidad: 1,},
    { id:22, nombre:'Marruecos', precio: 100, marca: "Puma", img:"img/marruecos.webp",cantidad: 1,},
    { id:23, nombre:'Croacia', precio: 100, marca: "Nike", img:"img/croacia.webp",cantidad: 1,},
    { id:24, nombre:'Brasil', precio: 100, marca: "Nike", img:"img/brasil.webp",cantidad: 1,},
    { id:25, nombre:'Serbia', precio: 100, marca: "Puma", img:"img/serbia.webp",cantidad: 1,},
    { id:26, nombre:'Suiza', precio: 100, marca: "Adidas", img:"img/suiza.webp",cantidad: 1,},
    { id:27, nombre:'Camerun', precio: 100, marca: "Lecoq", img:"img/cameru.jpg",cantidad: 1,},
    { id:28, nombre:'Portugal', precio: 100, marca: "Nike", img:"img/portugal.webp",cantidad: 1,},
    { id:29, nombre:'Ghana', precio: 100, marca: "Puma", img:"img/ghana.webp",cantidad: 1,},
    { id:30, nombre:'Uruguay', precio: 100, marca: "Puma", img:"img/uruguay.webp",cantidad: 1,},
    { id:31, nombre:'Corea del Sur', precio: 100, marca: "Nike", img:"img/corea.webp",cantidad: 1,},
    { id:32, nombre:'Inglaterra', precio: 100, marca: "Nike", img:"img/england.webp",cantidad: 1,}
]
